### ISSUE TITLE
sync time between esp-link and el-client

### ISSUE THREAD

**Issue by n3mawashi** [jeelabs/el-client#17]
hi, is it possible to sync time from the esp8266 with the 2.2beta2 firmware through the el-client to update time on the ardunio?

**Comment by tve** [comment]
I'm not sure whether it wouldn't be better to either use a REST request from the arduino to get the time from a server or to send time sync messages via MQTT. This way you avoid putting the esp8266's time sync in the middle...

**Comment by tve** [comment]
I forgot, there is a command to fetch the time: https://github.com/jeelabs/el-client/blob/master/ELClient/ELClientCmd.cpp#L7-L13
