### ISSUE TITLE
CRC Error Persistent With EL Client Rest Example

### ISSUE THREAD

**Issue by rupin** [jeelabs/el-client#18]
Hello,
We are currently experimenting with the EL Client Library with esp-link 2.2.3. When posting to thingspeak or to any website like google, we get a CRC error. Here is a debug log from the Arduino.

EL-Client starting!
ELC: got 128 @295: 2020 203E3539 3720 53 4C 49 50 3A 20 73 74 61 72 74 20 6F 72 20 65 6E 64 20 6C 65 6E 3D 30 20 69 6E 70 6B 74 3D 30 D A 20 20 20 37 39 35 3E 20 53 4C 49 50 3A 20 73 74 61 72 74 20 6F 72 20 65 6E 64 20 6C 65 6E 3D 31 30 20 69 6E 70 6B 74 3D 31 D A 20 20 20 37 39 35 3E 20 63 6D 64 50 61 72 73 65 50 61 63 6B 65 74 3A 20 63 6D 64 3D 31 20 61 72 67 63 3D 30 20 76 61 6C 75 65 3D
ELC: Invalid CRC
ELC: got 10 @295: 2 283 0 74 B6
RESP_V: 643
SYNC!
EL-Client synced!
ELC: got 128 @295: 2020 203E3630 3820 63 6D 64 41 64 64 43 62 3A 20 27 77 69 66 69 43 62 27 2D 3E 30 78 32 38 33 20 61 64 64 65 64 20 61 74 20 30 D A 20 20 20 38 31 30 20 20 32 34 31 39 3E 20 73 63 61 6E 64 6F 6E 65 D A 20 20 32 34 31 39 3E 20 73 74 61 74 65 3A 20 30 20 2D 3E 20 32 20 28 62 30 29 D A 20 20 32 34 32 31 3E 20 73 74 61 74 65 3A 20 32 20 2D 3E 20 33 20 28 30 29 D A 20 20 32
ELC: Invalid CRC
ELC: got 14 @295: 3 283 1 1 0 1 0 23 D8
RESP_CB: 643 1
WIFI NOT READY: 1
ELC: got 128 @295: 2020 203E3632 3133 69 70 3A 31 39 32 2E 31 36 38 2E 31 2E 31 33 31 2C 6D 61 73 6B 3A 32 35 35 2E 32 35 35 2E 32 35 35 2E 30 2C 67 77 3A 31 39 32 2E 31 36 38 2E 31 2E 31 D A 20 20 33 31 32 37 3E 20 57 69 66 69 20 67 6F 74 20 69 70 3A 31 39 32 2E 31 36 38 2E 31 2E 31 33 31 2C 6D 61 73 6B 3A 32 35 35 2E 32 35 35 2E 32 35 35 2E 30 2C 67 77 3A 31 39 32 2E 31 36 38 2E 31 2E 31 D
ELC: Invalid CRC
ELC: got 14 @295: 3 283 1 1 0 5 0 43 BF
RESP_CB: 643 1
WIFI CONNECTED
REST begin failed: -1

I am thinking there is no CRC error, but the code picks up the wrong byte to validate CRC error, and fails.

**Comment by tve** [comment]
A lot of the sync code has been rewritten since this issue was opened. Please reopen if this is still pertinent and you're still interested. Thank you.
