### ISSUE TITLE
Change message limit

### ISSUE THREAD

**Issue by FernandoGarcia** [jeelabs/el-client#28]
Hi @tve !

Firstly thanks for this library.

Where can I edit the limit for message size?

I can see this message on log:

```
MQTT Client: Received topic: ******/********/topic/command, data: 20,1,03,00,10,00,1,2,3,4,5,6,7,33,2,24,1,1,K
MQTT: Data cb=0x00000d00 topic=*******/********/topic/command20,1,03,00,10,00,1,2,3,4,5,6,7,33,2,24,1,1,K len=44
```

But the controller doesn't receive the message.

With messages smaller it's working very well.

Best regards.

PS: **** are private infos.

**Comment by tve** [comment]
https://github.com/jeelabs/el-client/blob/master/ELClient/ELClient.h#L128
I hope this helps!

**Comment by FernandoGarcia** [comment]
Hi @tve!

Thanks for your answer.

I changed it before to 350 and now to 550 but doesn't solve.

There another suggestion?

Best regards.

**Comment by FernandoGarcia** [comment]
It's working with buffer size of 128 but only with baud rate at 9600 I don't know the reason, maybe because I'm using jumper wires of 30 cm.

For smaller messages works with baud rate at 115200.

Thanks for your time.
